"""causal-worlds: fictional causal operations worlds with a ground-truth answer-key."""

from causal_worlds._version import __version__
from causal_worlds.admission import (
    FaithfulnessReport,
    check_faithfulness,
    is_nontrivial,
    population_covariance,
)
from causal_worlds.anonymize import anonymize_spec
from causal_worlds.artifact import LoadedBundle, Provenance, load_bundle, save_bundle
from causal_worlds.baselines import (
    BASELINES,
    BaselineResult,
    DagmaDiscoverer,
    DirectLingamDiscoverer,
    FciDiscoverer,
    GesDiscoverer,
    GiesDiscoverer,
    PcDiscoverer,
    pooled_interventional_sample,
)
from causal_worlds.bench import grade_bundle, grade_spec, grade_temporal_spec
from causal_worlds.brief import WorldBrief, is_complete, missing_fields, render
from causal_worlds.config import Settings
from causal_worlds.container import Container, build_container
from causal_worlds.control import (
    ControlObjective,
    ControlReport,
    CorrelationalController,
    InterventionalController,
    LeverIdentifiability,
    NonlinearControlError,
    PerturbationReport,
    control_substrate,
    default_objective,
    grade_control,
    grade_controller,
    is_control_identifiable,
    lever_effects,
    optimal_policy,
    regime_configs,
    regime_optimal_policy,
    regret_under_perturbation,
)
from causal_worlds.controls import (
    R2SortnregressDiscoverer,
    SortnregressDiscoverer,
    r2sortability,
    varsortability,
)
from causal_worlds.counterfactual import (
    CounterfactualResult,
    TemporalCounterfactualResult,
    abduct,
    counterfactual,
    counterfactual_temporal,
    predict,
)
from causal_worlds.difficulty import StructuralDifficulty, structural_difficulty
from causal_worlds.discover import InterventionalCiDiscoverer
from causal_worlds.elicit import (
    ClaudeElicitor,
    Session,
    build_claude_elicitor,
    force_ready,
    respond,
    start_session,
)
from causal_worlds.errors import BudgetExceededError, CausalWorldsError
from causal_worlds.evaluation import (
    Report,
    TemporalReport,
    directed_shd,
    f1,
    score,
    skeleton_shd,
    temporal_directed_shd,
    temporal_f1,
    temporal_score,
)
from causal_worlds.fakes import FakeAuthor, FakeElicitor, FakeJudge, FakeTemporalDiscoverer
from causal_worlds.gates import GateReport, run_gates
from causal_worlds.generate import AdmittedWorld, NotAdmittedError, generate
from causal_worlds.obs import LangfuseTracer, NullTracer, Tracer, build_langfuse_tracer
from causal_worlds.protocols import (
    Author,
    Controller,
    Discoverer,
    Edges,
    Elicitor,
    Gate,
    Judge,
    Substrate,
    TemporalDiscoverer,
    TemporalEdges,
)
from causal_worlds.sample import Sample, ScmSubstrate, build_substrate
from causal_worlds.schema import (
    AnswerKey,
    CyclicGraphError,
    DanglingReferenceError,
    DuplicateMechanismError,
    Mechanism,
    NonStationaryError,
    Role,
    RoleError,
    SpecError,
    Term,
    Transform,
    Variable,
    WorldSpec,
    answer_key,
    has_nonlinear_terms,
    temporal_answer_key,
    validate,
)
from causal_worlds.serde import WorldSpecModel, spec_from_json, spec_to_json
from causal_worlds.temporal_baselines import (
    TEMPORAL_BASELINES,
    GrangerDiscoverer,
    LpcmciDiscoverer,
    PcmciPlusDiscoverer,
    VarLingamDiscoverer,
)
from causal_worlds.viz import to_dot, to_mermaid

__all__ = [
    "BASELINES",
    "TEMPORAL_BASELINES",
    "AdmittedWorld",
    "AnswerKey",
    "Author",
    "BaselineResult",
    "BudgetExceededError",
    "CausalWorldsError",
    "ClaudeElicitor",
    "Container",
    "ControlObjective",
    "ControlReport",
    "Controller",
    "CorrelationalController",
    "CounterfactualResult",
    "CyclicGraphError",
    "DagmaDiscoverer",
    "DanglingReferenceError",
    "DirectLingamDiscoverer",
    "Discoverer",
    "DuplicateMechanismError",
    "Edges",
    "Elicitor",
    "FaithfulnessReport",
    "FakeAuthor",
    "FakeElicitor",
    "FakeJudge",
    "FakeTemporalDiscoverer",
    "FciDiscoverer",
    "Gate",
    "GateReport",
    "GesDiscoverer",
    "GiesDiscoverer",
    "GrangerDiscoverer",
    "InterventionalCiDiscoverer",
    "InterventionalController",
    "Judge",
    "LangfuseTracer",
    "LeverIdentifiability",
    "LoadedBundle",
    "LpcmciDiscoverer",
    "Mechanism",
    "NonStationaryError",
    "NonlinearControlError",
    "NotAdmittedError",
    "NullTracer",
    "PcDiscoverer",
    "PcmciPlusDiscoverer",
    "PerturbationReport",
    "Provenance",
    "R2SortnregressDiscoverer",
    "Report",
    "Role",
    "RoleError",
    "Sample",
    "ScmSubstrate",
    "Session",
    "Settings",
    "SortnregressDiscoverer",
    "SpecError",
    "StructuralDifficulty",
    "Substrate",
    "TemporalCounterfactualResult",
    "TemporalDiscoverer",
    "TemporalEdges",
    "TemporalReport",
    "Term",
    "Tracer",
    "Transform",
    "VarLingamDiscoverer",
    "Variable",
    "WorldBrief",
    "WorldSpec",
    "WorldSpecModel",
    "__version__",
    "abduct",
    "anonymize_spec",
    "answer_key",
    "build_claude_elicitor",
    "build_container",
    "build_langfuse_tracer",
    "build_substrate",
    "check_faithfulness",
    "control_substrate",
    "counterfactual",
    "counterfactual_temporal",
    "default_objective",
    "directed_shd",
    "f1",
    "force_ready",
    "generate",
    "grade_bundle",
    "grade_control",
    "grade_controller",
    "grade_spec",
    "grade_temporal_spec",
    "has_nonlinear_terms",
    "is_complete",
    "is_control_identifiable",
    "is_nontrivial",
    "lever_effects",
    "load_bundle",
    "missing_fields",
    "optimal_policy",
    "pooled_interventional_sample",
    "population_covariance",
    "predict",
    "r2sortability",
    "regime_configs",
    "regime_optimal_policy",
    "regret_under_perturbation",
    "render",
    "respond",
    "run_gates",
    "save_bundle",
    "score",
    "skeleton_shd",
    "spec_from_json",
    "spec_to_json",
    "start_session",
    "structural_difficulty",
    "temporal_answer_key",
    "temporal_directed_shd",
    "temporal_f1",
    "temporal_score",
    "to_dot",
    "to_mermaid",
    "validate",
    "varsortability",
]
